CONFIG = {
    ME_COLOR = '#000080', -- HEX COLOR FOR /ME
    DO_COLOR ='#DA14FF', -- HEX COLOR FOR /DO
    GME_COLOR = '#39FF14', -- HEX COLOR FOR /GME
    TWT_COLOR = '#1DA1F2', -- HEX COLOR FOR /TWT
    OOC_COLOR = '#FFA500', -- HEX COLOR FOR /OOC
    DARKWEB_COLOR = '#000000', -- HEX COLOR FOR /DARKWEB
    ADVERT_COLOR = '#FFDA14' -- HEX COLOR FOR /AD
}